export const CurrentObj = {
    id: 'current',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Current News',
    headline: 'We have acquired a property for our first Masjid!',
    description: 'Alhamdulillah by grace of Allah swt we are humbled to inform you that we have been successful in our bid in auction for St Peters Church, Pilkington Avenue, Westlands, Newcastle with a view to establish an Islamic Centre انشاء اللہ. We will need your help and support going forward to establish a Mosque and an Islamic Centre on the premises. ',
    buttonLabel: 'Donate',
    btnclick: 'donate',
    imgStart: false,
    img: require('../../images/church1.jpeg'),
    alt:'aqsa',
    dark: false,
    primary: false,
    darkText: true,
};