export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'About Us',
    headline: 'Insert a suitable headline in this space',
    description: 'Insert About Us text here',
    buttonLabel: 'Get started',
    btnclick: 'home',
    imgStart: false,
    img: require('../../images/svg-1.svg').default,
    // img: require('../../images/svg-1.svg').default,
    alt:'flowers',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'mission',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Our Mission',
    headline: 'Insert a suitable headline in this space',
    description: 'Insert Mission here',
    buttonLabel: 'Learn More',
    btnclick: 'home',
    imgStart: true,
    img: require('../../images/svg-2.svg').default,
    alt:'truck',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: 'donate',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Donations',
    headline: 'Donate via PayPal or through Bank Transfer with our details below',
    description: 'If you are making a large donation then please also fill out the Gift Aid Declaration Form.',
    buttonLabel: 'Donate',
    btnclick: 'home',
    imgStart: false,
    img: require('../../images/svg-3.svg').default,
    alt:'park',
    dark: false,
    primary: false,
    darkText: true,
};