export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'About Us',
    headline: 'A group of volunteers coming together to provide for the Muslims.',
    description: 'Starting at the Royal Stoke Hospital Prayer Room, we agreed that we wanted to create a space where all Muslims can pray in Newcastle Under Lyme.',
    buttonLabel: 'Get started',
    btnclick: 'mission',
    imgStart: false,
    img: require('../../images/svg-5.svg').default,
    // img: require('../../images/svg-1.svg').default,
    alt:'flowers',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'mission',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Our Mission',
    headline: 'To promote the teachings and tenets of Islam.',
    description: ' We want to provide a place of worship as well as facilities for islamic education, in Newcastle Under Lyme and beyond, and follow the teachings of the Quran and the Sunnah of Prophet Muhammad ﷺ.',
    buttonLabel: 'Learn More',
    btnclick: 'services',
    imgStart: true,
    img: require('../../images/svg-2.svg').default,
    alt:'truck',
    dark: false,
    primary: false,
    darkText: true,
};